# Generated by Django 5.0 on 2024-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_rename_book_cake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
