# Generated by Django 5.0 on 2024-02-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_cake_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='follow_author',
        ),
    ]
