# Generated by Django 5.0 on 2024-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_rename_created_order_created_at_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='bakery_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
